######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 15 14:06:03 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += webslidesapp.h
SOURCES += main.cpp webslidesapp.cpp

QT += webkit

